{{- if ne .Values.global.mode "quickstart" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  {{- with .Values.mysql }}
  mysql.db.name: {{ .database }}
  mysql.port: "3306"
  mysql.user: {{ .user }}
  mysql.password: {{ .password }}
  {{- end }}
  {{- else if or (eq .Values.global.mode "standalone") (eq .Values.global.mode "cluster") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  {{- with .Values.custom.db }}
  mysql.db.host: {{.host}}
  mysql.db.name: {{ .name }}
  mysql.port: {{ .port }}
  mysql.user: {{ .username }}
  mysql.password: {{ .password }}
  {{- end }}
  {{- end }}



