{{- if eq .Values.global.mode "quickstart" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
{{- with .Values.mysql }}
data:
  mysql.db.name: {{ .database }}
  mysql.port: "3306"
  mysql.user: {{ .user }}
  mysql.password: {{ .password }}
{{- end }}
{{- else if eq .Values.global.mode "standalone" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
{{- with .Values.custom.db }}
data:
  mysql.db.host: {{ .host }}
  mysql.db.name: {{ .name }}
  mysql.port: {{ .port }}
  mysql.user: {{ .username }}
  mysql.password: {{ .password }}
{{- end }}
{{- else if eq .Values.global.mode "cluster" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
{{- with .Values.custom.db }}
data:
  mysql.db.host: {{ .host }}
  mysql.db.name: {{ .name }}
  mysql.port: {{ .port }}
  mysql.user: {{ .username }}
  mysql.password: {{ .password }}
{{- end }}
{{- end }}
